export const blackDown = {
    '1': 'white_rook',
    '2': 'white_knight',
    '3': 'white_bishop',
    '4': 'white_queen',
    '5': 'white_king',
    '6': 'white_bishop',
    '7': 'white_knight',
    '8': 'white_rook',
    '9': 'white_pawn',
    '10': 'white_pawn',
    '11': 'white_pawn',
    '12': 'white_pawn',
    '13': 'white_pawn',
    '14': 'white_pawn',
    '15': 'white_pawn',
    '16': 'white_pawn',

    '49': 'black_rook',
    '50': 'black_knight',
    '51': 'black_bishop',
    '52': 'black_queen',
    '53': 'black_king',
    '54': 'black_bishop',
    '55': 'black_knight',
    '56': 'black_rook',
    '57': 'black_pawn',
    '58': 'black_pawn',
    '59': 'black_pawn',
    '60': 'black_pawn',
    '61': 'black_pawn',
    '62': 'black_pawn',
    '63': 'black_pawn',
    '64': 'black_pawn',
}